# Generated by Django 4.1.2 on 2022-11-22 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='Название книги')),
                ('desk', models.TextField(verbose_name='Дескриптор')),
                ('author', models.CharField(max_length=512, verbose_name='Автор книги')),
                ('time_create', models.DateTimeField(verbose_name='Дата создания')),
                ('photo1', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фото 1')),
                ('photo2', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фото 2')),
                ('photo3', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фото 3')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Когда добавлен')),
                ('likenolike', models.IntegerField(verbose_name='Сколькам пользователям понравился')),
                ('userbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
                'ordering': ['id'],
            },
        ),
    ]
