# Generated by Django 4.1.2 on 2022-11-22 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justchat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book',
            field=models.FileField(default=1, upload_to='books/%Y/%m/%d/', verbose_name='Книга'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='likenolike',
            field=models.IntegerField(default=0, verbose_name='Сколькам пользователям понравился'),
        ),
    ]
