# Generated by Django 4.1.2 on 2022-12-13 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('justchat', '0002_book_book_alter_book_likenolike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='time_create',
        ),
    ]
